package com.service.manager.user.persistence.mapper;

import com.service.manager.user.persistence.ProductSubCategory;
import com.service.manager.user.persistence.ProductSubCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSubCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int countByExample(ProductSubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByExample(ProductSubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByPrimaryKey(Integer subCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insert(ProductSubCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insertSelective(ProductSubCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    List<ProductSubCategory> selectByExample(ProductSubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    ProductSubCategory selectByPrimaryKey(Integer subCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExampleSelective(@Param("record") ProductSubCategory record, @Param("example") ProductSubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExample(@Param("record") ProductSubCategory record, @Param("example") ProductSubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByPrimaryKeySelective(ProductSubCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sub_category
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByPrimaryKey(ProductSubCategory record);
    
    List<ProductSubCategory> getAllSubCategories();
    
    List<ProductSubCategory>  getAllCategories();
    
    List<ProductSubCategory> getCategoriesByCategoryId(@Param("categoryId") Integer categoryId);
    
    List<ProductSubCategory> getCategoriesByCategoryName();
}