package com.service.manager.user.persistence.mapper;

import com.service.manager.user.persistence.RequestDetails;
import com.service.manager.user.persistence.RequestDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int countByExample(RequestDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByExample(RequestDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByPrimaryKey(Integer requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insert(RequestDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insertSelective(RequestDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    List<RequestDetails> selectByExample(RequestDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    RequestDetails selectByPrimaryKey(Integer requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExampleSelective(@Param("record") RequestDetails record, @Param("example") RequestDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExample(@Param("record") RequestDetails record, @Param("example") RequestDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByPrimaryKeySelective(RequestDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_details
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByPrimaryKey(RequestDetails record);
    
    List<RequestDetails> fetchAllRequestDetails();
    
    List<RequestDetails> fetchAllRequestDetailsForUser(@Param("userMobileNo") Long userMobileNo);
    
}