package com.service.manager.user.persistence.mapper;

import com.service.manager.user.persistence.SubCategoryTypeExample;
import com.service.manager.user.persistence.SubCategoryTypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubCategoryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int countByExample(SubCategoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByExample(SubCategoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByPrimaryKey(SubCategoryTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insert(SubCategoryTypeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insertSelective(SubCategoryTypeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    List<SubCategoryTypeKey> selectByExample(SubCategoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExampleSelective(@Param("record") SubCategoryTypeKey record, @Param("example") SubCategoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_category_type
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExample(@Param("record") SubCategoryTypeKey record, @Param("example") SubCategoryTypeExample example);
}