package com.service.manager.user.persistence.mapper;

import com.service.manager.user.persistence.UserAddressesExample;
import com.service.manager.user.persistence.UserAddressesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAddressesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int countByExample(UserAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByExample(UserAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByPrimaryKey(UserAddressesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insert(UserAddressesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insertSelective(UserAddressesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    List<UserAddressesKey> selectByExample(UserAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExampleSelective(@Param("record") UserAddressesKey record, @Param("example") UserAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addresses
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExample(@Param("record") UserAddressesKey record, @Param("example") UserAddressesExample example);
}