package com.sajag.manager.persistence.mapper;

import com.sajag.manager.persistence.Complaints;
import com.sajag.manager.persistence.ComplaintsExample;
import com.sajag.manager.persistence.UserComplaintsKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ComplaintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int countByExample(ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByExample(ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByPrimaryKey(Integer complaintId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insert(Complaints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insertSelective(Complaints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    List<Complaints> selectByExample(ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    Complaints selectByPrimaryKey(Integer complaintId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExampleSelective(@Param("record") Complaints record, @Param("example") ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExample(@Param("record") Complaints record, @Param("example") ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByPrimaryKeySelective(Complaints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByPrimaryKey(Complaints record);
    
}