package com.sajag.manager.persistence.mapper;

import com.sajag.manager.persistence.ComplaintImagesExample;
import com.sajag.manager.persistence.ComplaintImagesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplaintImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int countByExample(ComplaintImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByExample(ComplaintImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByPrimaryKey(ComplaintImagesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insert(ComplaintImagesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insertSelective(ComplaintImagesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    List<ComplaintImagesKey> selectByExample(ComplaintImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExampleSelective(@Param("record") ComplaintImagesKey record, @Param("example") ComplaintImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint_images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExample(@Param("record") ComplaintImagesKey record, @Param("example") ComplaintImagesExample example);
}