package com.sajag.manager.persistence.mapper;

import com.sajag.manager.persistence.Departments;
import com.sajag.manager.persistence.DepartmentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int countByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insert(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insertSelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    List<Departments> selectByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    Departments selectByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExampleSelective(@Param("record") Departments record, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExample(@Param("record") Departments record, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByPrimaryKeySelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByPrimaryKey(Departments record);
}