package com.sajag.manager.persistence.mapper;

import com.sajag.manager.persistence.Images;
import com.sajag.manager.persistence.ImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int countByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insertSelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    List<Images> selectByExampleWithBLOBs(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    List<Images> selectByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    Images selectByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExampleSelective(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExample(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByPrimaryKeySelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Images record);
    
    public Images selectImageByImageData(Images record);
    
    int insertWithKey(@Param("image") Images image);
}