package com.sajag.manager.persistence.mapper;

import com.sajag.manager.persistence.UserComplaintsExample;
import com.sajag.manager.persistence.UserComplaintsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserComplaintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int countByExample(UserComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByExample(UserComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int deleteByPrimaryKey(UserComplaintsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insert(UserComplaintsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int insertSelective(UserComplaintsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    List<UserComplaintsKey> selectByExample(UserComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExampleSelective(@Param("record") UserComplaintsKey record, @Param("example") UserComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_complaints
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    int updateByExample(@Param("record") UserComplaintsKey record, @Param("example") UserComplaintsExample example);
    
    List<UserComplaintsKey> getAllComplaints();
    List<UserComplaintsKey> getAllUserComplaints(Long userMobileNo);
}