package com.service.manager.user.persistence.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.service.manager.user.persistence.Complaints;
import com.service.manager.user.persistence.ComplaintsExample;

public interface ComplaintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int countByExample(ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByExample(ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int deleteByPrimaryKey(Integer complaintId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insert(Complaints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int insertSelective(Complaints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    List<Complaints> selectByExample(ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    Complaints selectByPrimaryKey(Integer complaintId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExampleSelective(@Param("record") Complaints record, @Param("example") ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByExample(@Param("record") Complaints record, @Param("example") ComplaintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByPrimaryKeySelective(Complaints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaints
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    int updateByPrimaryKey(Complaints record);
    
    List<Complaints> getComplaintByDetails(@Param("comments") String comments,@Param("complaintStatus") String complaintStatus,@Param("createDate") Date createDate,@Param("lastUpdateDate") Date lastUpdateDate);
}