package com.shiv.mybatis.demo.component.persistence;

public class EmpDeptKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dept.emp_id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    private Long empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dept.dept_id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    private Long deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dept.emp_id
     *
     * @return the value of emp_dept.emp_id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dept.emp_id
     *
     * @param empId the value for emp_dept.emp_id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dept.dept_id
     *
     * @return the value of emp_dept.dept_id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dept.dept_id
     *
     * @param deptId the value for emp_dept.dept_id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }
}