package com.shiv.mybatis.demo.component.persistence;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.fname
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.lname
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    private String lname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.address
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.fname
     *
     * @return the value of employee.fname
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.fname
     *
     * @param fname the value for employee.fname
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public void setFname(String fname) {
        this.fname = fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.lname
     *
     * @return the value of employee.lname
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.lname
     *
     * @param lname the value for employee.lname
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public void setLname(String lname) {
        this.lname = lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.address
     *
     * @return the value of employee.address
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.address
     *
     * @param address the value for employee.address
     *
     * @mbggenerated Wed Jan 11 09:43:15 IST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }
}