package com.service.manager.user.persistence;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.first_line
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private String firstLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.street_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.pincode
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer pincode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.state
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_id
     *
     * @param addressId the value for address.address_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.first_line
     *
     * @return the value of address.first_line
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public String getFirstLine() {
        return firstLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.first_line
     *
     * @param firstLine the value for address.first_line
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setFirstLine(String firstLine) {
        this.firstLine = firstLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.street_name
     *
     * @return the value of address.street_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.street_name
     *
     * @param streetName the value for address.street_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.pincode
     *
     * @return the value of address.pincode
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getPincode() {
        return pincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.pincode
     *
     * @param pincode the value for address.pincode
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.state
     *
     * @return the value of address.state
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.state
     *
     * @param state the value for address.state
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setState(String state) {
        this.state = state;
    }
}