package com.service.manager.user.persistence;

public class CategorySubCategoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_sub_category.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_sub_category.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer subCategoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_sub_category.category_id
     *
     * @return the value of category_sub_category.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_sub_category.category_id
     *
     * @param categoryId the value for category_sub_category.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_sub_category.sub_category_id
     *
     * @return the value of category_sub_category.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getSubCategoryId() {
        return subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_sub_category.sub_category_id
     *
     * @param subCategoryId the value for category_sub_category.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }
}