package com.service.manager.user.persistence;

public class RequestDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_details.request_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_details.product_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_details.user_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_details.request_id
     *
     * @return the value of request_details.request_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_details.request_id
     *
     * @param requestId the value for request_details.request_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_details.product_id
     *
     * @return the value of request_details.product_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_details.product_id
     *
     * @param productId the value for request_details.product_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_details.user_id
     *
     * @return the value of request_details.user_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_details.user_id
     *
     * @param userId the value for request_details.user_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}