package com.service.manager.user.persistence;

public class SubCategoryTypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_category_type.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer subCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_category_type.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_category_type.sub_category_id
     *
     * @return the value of sub_category_type.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getSubCategoryId() {
        return subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_category_type.sub_category_id
     *
     * @param subCategoryId the value for sub_category_type.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_category_type.type_id
     *
     * @return the value of sub_category_type.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_category_type.type_id
     *
     * @param typeId the value for sub_category_type.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}