package com.sajag.manager.persistence;

public class ComplaintImagesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint_images.complaint_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private Integer complaintId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint_images.image_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private Integer imageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint_images.complaint_id
     *
     * @return the value of complaint_images.complaint_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public Integer getComplaintId() {
        return complaintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint_images.complaint_id
     *
     * @param complaintId the value for complaint_images.complaint_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setComplaintId(Integer complaintId) {
        this.complaintId = complaintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint_images.image_id
     *
     * @return the value of complaint_images.image_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint_images.image_id
     *
     * @param imageId the value for complaint_images.image_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
}