package com.sajag.manager.persistence;

public class Images {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.image_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private Integer imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.image_data
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private byte[] imageData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.image_id
     *
     * @return the value of images.image_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.image_id
     *
     * @param imageId the value for images.image_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.image_data
     *
     * @return the value of images.image_data
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public byte[] getImageData() {
        return imageData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.image_data
     *
     * @param imageData the value for images.image_data
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setImageData(byte[] imageData) {
        this.imageData = imageData;
    }
}