package com.sajag.manager.persistence;

public class UserComplaintsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_complaints.user_mobile
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private Long userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_complaints.complaint_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private Integer complaintId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_complaints.user_mobile
     *
     * @return the value of user_complaints.user_mobile
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public Long getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_complaints.user_mobile
     *
     * @param userMobile the value for user_complaints.user_mobile
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setUserMobile(Long userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_complaints.complaint_id
     *
     * @return the value of user_complaints.complaint_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public Integer getComplaintId() {
        return complaintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_complaints.complaint_id
     *
     * @param complaintId the value for user_complaints.complaint_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setComplaintId(Integer complaintId) {
        this.complaintId = complaintId;
    }
}