package com.sajag.manager.persistence;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_no
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private Long mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_name
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_name
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private String emailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.blood_group
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private String bloodGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pincode
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    private Integer pincode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_no
     *
     * @return the value of user.mobile_no
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public Long getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_no
     *
     * @param mobileNo the value for user.mobile_no
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setMobileNo(Long mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.first_name
     *
     * @return the value of user.first_name
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.first_name
     *
     * @param firstName the value for user.first_name
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_name
     *
     * @return the value of user.last_name
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_name
     *
     * @param lastName the value for user.last_name
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_id
     *
     * @return the value of user.email_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public String getEmailId() {
        return emailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_id
     *
     * @param emailId the value for user.email_id
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.blood_group
     *
     * @return the value of user.blood_group
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public String getBloodGroup() {
        return bloodGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.blood_group
     *
     * @param bloodGroup the value for user.blood_group
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pincode
     *
     * @return the value of user.pincode
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public Integer getPincode() {
        return pincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pincode
     *
     * @param pincode the value for user.pincode
     *
     * @mbggenerated Fri Apr 21 12:47:03 IST 2017
     */
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }
}