package com.service.manager.user.persistence;

public class ProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.type_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.type_id
     *
     * @return the value of product_type.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.type_id
     *
     * @param typeId the value for product_type.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.type_name
     *
     * @return the value of product_type.type_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.type_name
     *
     * @param typeName the value for product_type.type_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}