package com.service.manager.user.persistence;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer subCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sub_category_id
     *
     * @return the value of product.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getSubCategoryId() {
        return subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sub_category_id
     *
     * @param subCategoryId the value for product.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type_id
     *
     * @return the value of product.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type_id
     *
     * @param typeId the value for product.type_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}