package com.service.manager.user.persistence;

public class ProductSubCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sub_category.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer subCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sub_category.sub_category_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private String subCategoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sub_category.sub_category_id
     *
     * @return the value of product_sub_category.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getSubCategoryId() {
        return subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sub_category.sub_category_id
     *
     * @param subCategoryId the value for product_sub_category.sub_category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sub_category.sub_category_name
     *
     * @return the value of product_sub_category.sub_category_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public String getSubCategoryName() {
        return subCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sub_category.sub_category_name
     *
     * @param subCategoryName the value for product_sub_category.sub_category_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }
}