package com.service.manager.user.persistence;

public class ProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_id
     *
     * @return the value of product_category.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_id
     *
     * @param categoryId the value for product_category.category_id
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_name
     *
     * @return the value of product_category.category_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_name
     *
     * @param categoryName the value for product_category.category_name
     *
     * @mbggenerated Sun Feb 12 00:05:38 IST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
}